In [1]:
import open3d as o3d
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
pcd = o3d.io.read_point_cloud('../data/points/Armadillo/Armadillo.pcd')
print('正在加载点云...\n', pcd)
# o3d.visualization.draw_geometries([pcd])

正在加载点云...
 PointCloud with 172974 points.


In [5]:
# 体素下采样
# 将点云进行体素划分
# 对所有非空体素，取体素内部点云的质心作为该体素的点的位置
voxel_size = 3
downpcd = pcd.voxel_down_sample(voxel_size)
print('正在可视化下采样点云...', downpcd)
o3d.visualization.draw_geometries([downpcd])

正在可视化下采样点云... PointCloud with 5792 points.


In [6]:
# 统计滤波：去除点云中的离群噪声点
# 对每个点，找到它num_neighbours个最近邻点，计算所有邻点到该点的平均距离
# 计算所有点平均距离的均值和标准差，并保留平均距离在阈值范围内的点

num_neighbours = 30 # K邻域点的个数，对每个点，计算其周围20个最近邻点
std_ratio = 2.0 # 标准差倍数阈值，用于判断离群点

# 执行统计滤波，返回滤波后的干净点云阵列sor_pcd和对应的索引idx
sor_pcd, idx = pcd.remove_statistical_outlier(num_neighbours, std_ratio)
sor_pcd.paint_uniform_color([0, 0, 1])
print('滤波统计后的点云', sor_pcd)

# 提取噪声点云
# invert=True为反选索引，即选择未被保留的点（噪声）
sor_noise_pcd = pcd.select_by_index(idx, invert=True)
print('噪声点云：', sor_noise_pcd)
sor_noise_pcd.paint_uniform_color([1, 0, 0])

o3d.visualization.draw_geometries([sor_pcd, sor_noise_pcd])

滤波统计后的点云 PointCloud with 168116 points.
噪声点云： PointCloud with 4858 points.


In [7]:
# 半径滤波
# 与统计滤波不同，它基于固定半径范围内的点数来去除离群点
# 对点云中每个点，在以该点为球心、radius为半径的球体内搜索邻域点
# 统计该球体内的点数，如果点数 ≥ num_neighbours，保留该点；否则视为噪声点

num_neighbours = 1300
radius = 10 # 搜索半径大小

sor_pcd, idx = pcd.remove_radius_outlier(num_neighbours, radius)
sor_pcd.paint_uniform_color([0, 0, 1])
print('半径滤波后的点云：', sor_pcd)

sor_noise_pcd = pcd.select_by_index(idx, invert=True)
print('噪声点云：', sor_noise_pcd)
sor_noise_pcd.paint_uniform_color([1, 0, 0])

o3d.visualization.draw_geometries([sor_pcd, sor_noise_pcd])

半径滤波后的点云： PointCloud with 170664 points.
噪声点云： PointCloud with 2310 points.


In [11]:
# 点云提取特征
# 法线估计

print('->正在估计法线并可视化...')
radius = 0.01
max_nn = 30 # 领域内用于估计法线的最大点数

pcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius, max_nn))
o3d.visualization.draw_geometries([pcd], point_show_normal=True)

# [0. 0. 1.]表示沿着Z轴正方向
print('正在打印前10个点的法向量...')
print(np.asarray(pcd.normals)[:10, :])

->正在估计法线并可视化...
正在打印前10个点的法向量...
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0.