In [2]:
import numpy as np
import torch

In [4]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [5]:
array = np.array([1, 2, 3])
tensor = torch.from_numpy(array)
print(tensor)

tensor([1, 2, 3], dtype=torch.int32)


In [7]:
tensor_2d = torch.tensor([[1, 2, 3], 
                          [4, 5, 6],
                          [7, 8, 9]])
print(tensor_2d, tensor_2d.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.Size([3, 3])


In [8]:
# 创建 3D 张量（立方体）
tensor_3d = torch.stack([tensor_2d, tensor_2d + 10, tensor_2d - 5])
print(tensor_3d, tensor_3d.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]],

        [[-4, -3, -2],
         [-1,  0,  1],
         [ 2,  3,  4]]]) torch.Size([3, 3, 3])


In [9]:
# 创建 4D 张量（向量的立方体）
tensor_4d = torch.stack([tensor_3d, tensor_3d + 100])  # 堆叠 2 个 3D 张量
print("4D Tensor (Vector of Cubes):\n", tensor_4d)
print("Shape:", tensor_4d.shape)  # 形状

4D Tensor (Vector of Cubes):
 tensor([[[[  1,   2,   3],
          [  4,   5,   6],
          [  7,   8,   9]],

         [[ 11,  12,  13],
          [ 14,  15,  16],
          [ 17,  18,  19]],

         [[ -4,  -3,  -2],
          [ -1,   0,   1],
          [  2,   3,   4]]],


        [[[101, 102, 103],
          [104, 105, 106],
          [107, 108, 109]],

         [[111, 112, 113],
          [114, 115, 116],
          [117, 118, 119]],

         [[ 96,  97,  98],
          [ 99, 100, 101],
          [102, 103, 104]]]])
Shape: torch.Size([2, 3, 3, 3])


In [15]:
# 创建 5D 张量（矩阵的立方体）
tensor_5d = torch.stack([tensor_4d, tensor_4d + 1000])  # 堆叠 2 个 4D 张量
print("5D Tensor (Matrix of Cubes):\n", tensor_5d)
print("Shape:", tensor_5d.shape, tensor_5d.dim)  # 形状

5D Tensor (Matrix of Cubes):
 tensor([[[[[   1,    2,    3],
           [   4,    5,    6],
           [   7,    8,    9]],

          [[  11,   12,   13],
           [  14,   15,   16],
           [  17,   18,   19]],

          [[  -4,   -3,   -2],
           [  -1,    0,    1],
           [   2,    3,    4]]],


         [[[ 101,  102,  103],
           [ 104,  105,  106],
           [ 107,  108,  109]],

          [[ 111,  112,  113],
           [ 114,  115,  116],
           [ 117,  118,  119]],

          [[  96,   97,   98],
           [  99,  100,  101],
           [ 102,  103,  104]]]],



        [[[[1001, 1002, 1003],
           [1004, 1005, 1006],
           [1007, 1008, 1009]],

          [[1011, 1012, 1013],
           [1014, 1015, 1016],
           [1017, 1018, 1019]],

          [[ 996,  997,  998],
           [ 999, 1000, 1001],
           [1002, 1003, 1004]]],


         [[[1101, 1102, 1103],
           [1104, 1105, 1106],
           [1107, 1108, 1109]],

          [[

In [20]:
tensor_5d.is_contiguous()

True

In [21]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

print(tensor)
print(tensor.shape)
print(tensor.size())
print(tensor.dtype)
print(tensor.device)
print(tensor.dim())
print(tensor.numel())
print(tensor.requires_grad)
print(tensor.is_cuda)
print(tensor.is_contiguous())

single_value = torch.tensor(42)
print(single_value.item())

tensor_T = tensor.T
print(tensor_T)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
torch.Size([2, 3])
torch.float32
cpu
2
6
False
False
True
42
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [28]:
# 创建一个 2D 张量
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print("原始张量:\n", tensor)

# 1. **索引和切片操作**
print("\n【索引和切片】")
print("获取第一行:", tensor[0])  # 获取第一行
print("获取第一行第一列的元素:", tensor[0, 0])  # 获取特定元素
print("获取第二列的所有元素:", tensor[:, 1])  # 获取第二列所有元素

# 2. **形状变换操作**
print("\n【形状变换】")
reshaped = tensor.view(3, 2)  # 改变张量形状为 3x2
print("改变形状后的张量:\n", reshaped)
flattened = tensor.flatten()  # 将张量展平成一维
print("展平后的张量:\n", flattened)

# 3. **数学运算操作**
print("\n【数学运算】")
tensor_add = tensor + 10  # 张量加法
print("张量加 10:\n", tensor_add)
tensor_mul = tensor * 2  # 张量乘法
print("张量乘 2:\n", tensor_mul)
tensor_sum = tensor.sum()  # 计算所有元素的和
print("张量元素的和:", tensor_sum.item())

# 4. **与其他张量的操作**
print("\n【与其他张量操作】")
tensor2 = torch.tensor([[1, 1, 1], [1, 1, 1]], dtype=torch.float32)
print("另一个张量:\n", tensor2)
tensor_dot = torch.matmul(tensor2, tensor2.T)  # 张量矩阵乘法
print("矩阵乘法结果:\n", tensor_dot)
print(tensor2 @ tensor2.T)

# 5. **条件判断和筛选**
print("\n【条件判断和筛选】")
mask = tensor > 3  # 创建一个布尔掩码
print("大于 3 的元素的布尔掩码:\n", mask)
filtered_tensor = tensor[tensor > 3]  # 筛选出符合条件的元素
print("大于 3 的元素:\n", filtered_tensor)


原始张量:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])

【索引和切片】
获取第一行: tensor([1., 2., 3.])
获取第一行第一列的元素: tensor(1.)
获取第二列的所有元素: tensor([2., 5.])

【形状变换】
改变形状后的张量:
 tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
展平后的张量:
 tensor([1., 2., 3., 4., 5., 6.])

【数学运算】
张量加 10:
 tensor([[11., 12., 13.],
        [14., 15., 16.]])
张量乘 2:
 tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
张量元素的和: 21.0

【与其他张量操作】
另一个张量:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
矩阵乘法结果:
 tensor([[3., 3.],
        [3., 3.]])
tensor([[3., 3.],
        [3., 3.]])

【条件判断和筛选】
大于 3 的元素的布尔掩码:
 tensor([[False, False, False],
        [ True,  True,  True]])
大于 3 的元素:
 tensor([4., 5., 6.])


In [31]:
# GPU加速
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = torch.tensor([1, 2, 3], device=device)
x.is_cuda, x.device

(True, device(type='cuda', index=0))

device(type='cpu')

In [35]:
# Tensor与numpy相互转换操作
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])
print(numpy_array)
tensor_from_numpy = torch.from_numpy(numpy_array)
print(tensor_from_numpy)

numpy_array[0, 0] = 100
print(tensor_from_numpy)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
tensor([[100,   2,   3],
        [  4,   5,   6]], dtype=torch.int32)


In [37]:
tensor = torch.tensor([[7, 8, 9], [10, 11, 12]], dtype=torch.float32)
numpy_from_tensor = tensor.numpy()
print(numpy_from_tensor)

tensor[0, 0] = 100
print(numpy_from_tensor)

[[ 7.  8.  9.]
 [10. 11. 12.]]
[[100.   8.   9.]
 [ 10.  11.  12.]]


In [38]:
tensor_independent = torch.tensor([[13, 14, 15], [16, 17, 18]], dtype=torch.float32)
numpy_independent = tensor_independent.clone().numpy()
print(tensor_independent, numpy_independent)

tensor_independent[0, 0] = 100
print(numpy_independent)

tensor([[13., 14., 15.],
        [16., 17., 18.]]) [[13. 14. 15.]
 [16. 17. 18.]]
[[13. 14. 15.]
 [16. 17. 18.]]
